### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by sam-gurdus** [spacehuhn/esp8266_beaconSpam#12]

**Comment by 13r1ckz** [comment]
if you would have read the README you would see the text: "Note: This is a side project emerged from my ESP8266 Deauther.
Please have a look at this project first, the installation steps are the same." right under his patreon link.

next time please read the README first before you have any questions because that is what the README is for.

**Comment by sam-gurdus** [comment]
Chill. There is no reason to be so hostile. I wasn't able to find a .bin file, so I was unsure what to do next.

**Comment by sam-gurdus** [comment]
Has anyone precompiled this, or do I have to do it myself?

**Comment by 13r1ckz** [comment]
sorry if I came across hostile my plan was to lay down the facts. but, you can just download the bin file and espflasher link on the deauther github README.
and how to use the espflasher is just on the github README of the flasher its self.

**Comment by spacehuhn** [comment]
No worries guys, I added installation instructions now :)
